export const COOPERATIVE_MAP: Record<string, string> = {
    TESTING: "testing",
    NSCDCKWACOOP: "nscdckwacoop",
    NSCDCJOS: "nscdcjos",
    CTLS: "ctls",
    FUSION: "fusion",
    LIFELINEMCS: "lifelinemcs",
    TFC: "tfc",
    IMMIGRATION: "immigrationmcs",
    IMMIGRATIONMCS: "immigrationmcs",
    OCTICS: "octics",
    MILLY: "milly",
    AVIATIONABJ: "aviationabj",
    FCDAMCS: "fcdamcs",
    INECBAUCHI: "inecbauchi",
    INECKWARA: "ineckwara",
    GPMS: "gpms",
    INECHQMCS: "inechqmcs",
    NNMCSL: "nnmcsl",
    INECSMCS: "inecsmcs",
    MODACS: "modacs",
    NCCMCS: "nccmcs",
    NICNMCS: "nicnmcs",
    OAGF: "oagf",
    SAMCOS: "samcos",
    VALGEECS: "valgeecs",
  };