export enum AuthState {
    NEED_COOPERATIVE = "NEED_COOPERATIVE",
    NEED_CREDENTIALS = "NEED_CREDENTIALS",
    NEED_OTP = "NEED_OTP",
    AUTHENTICATED = "AUTHENTICATED",
    FAILED = "FAILED",
  }